### PR TITLE
Update to 1.0.4

### PR DESCRIPTION
**Pull request by dschreij**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dschreij** [comment]
@conda-forge/core. Any idea why the cmake command is not available in the Windows builds? Should the cmake entry in meta.yaml be moved from build to host?

**Comment by mariusvniekerk** [comment]
Try changing the bld.bat .  Its looking for cmake in the wrong place on windows

**Comment by dschreij** [comment]
@conda-forge/core The Windows build succeeds on Azure but fails on Appveyor. I remember from a previous occasion that this is no showstopper, but just to be sure: can I merge this PR with a failing Appveyor build?

**Comment by ocefpaf** [comment]
> @conda-forge/core The Windows build succeeds on Azure but fails on Appveyor. I remember from a previous occasion that this is no showstopper, but just to be sure: can I merge this PR with a failing Appveyor build?

You need to change the windows provider to Azure first.

add `provider: {win: azure}` to the `conda-forge.yml` file and re-render.

**Pull request merged**
