### PR TITLE
Add osx-arm64 and linux-aarch64 builds

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to be merged @dschreij.
Summary:
- It adds builds for osx-arm64 + linux-aarch64
- It uses sourceforge as download source, to avoid the spurious bot PRs in this repo
- It fixes the win-64 build, as the lrint function is now provided by the compiler
- It unpins sdl2 so it is compatible with recent builds of conda-forge sdl2

**Comment by Tobias-Fischer** [comment]
Kind reminder @dschreij

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/help-osx-arm64  any chance you could merge here please? The maintainers seem unresponsive. I’ve got no interest in maintaining the feedstock.

**Review by xhochy — APPROVED** [review]

**Pull request merged**
